### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by gabsdocompiuter** [osguri/tuquersabermais#4]
- [ ] Página Playlist
   - [x] Buscar dados do RSS (#1) e transformar em Json
   - [x] Carregar json em um flatlist
   - [x] Criar componente para a lista
      - [x] Preview do vídeo
      - [x] Título
      - [x] Descrição
      - [x] criar evento onPress
   - [ ] Mostrar vídeo ao clicar no item do flatlist #2 

---

- [x] Página Sobre
   - [x] Colocar foto centralizada e com borda circular
   - [x] Colocar textinho sobre o Wagner
